### PR TITLE
run rust programs in input-tester

### PR DESCRIPTION
**Pull request by Aj0SK**
From my point of view(beginner in Rust) it's as easy to test rust programs as is C++ programs.

### CODE REVIEW

**Review by jablkoj — APPROVED** [review]
Looks good to me

**Comment by matusf** [comment]
Not sure whether it is relevant, but we might consider adding optimisation option. From [man page](https://www.mankier.com/1/rustc):
`-C opt-level=val       -- optimize with possible levels 0-3` or `-O`

**Comment by Aj0SK** [comment]
> Not sure whether it is relevant, but we might consider adding optimisation option. From [man page](https://www.mankier.com/1/rustc):
> `-C opt-level=val -- optimize with possible levels 0-3` or `-O`

I wasn't sure about this. I don't see that well into rust and it's optimizations right now and found it unnecessary for now to optimize it. I thought that only reason why is C++ compiled with -O2 is that Jano wanted to match flags that are used in testovac...

**Review by jablkoj — CHANGES_REQUESTED** [review]
Actually I think adding optimization flags is a good idea. Please add -O2 or something equivalent.

**Review by jablkoj — APPROVED** [review]
like

**Pull request merged**
